export const list = [
  { id: 1, type: "text", content: "这是第一条消息，内容简单明了。" },
  { id: 2, type: "photo", content: "https://example.com/photo1.jpg" },
  { id: 3, type: "text", content: "今天的天气真不错，适合外出活动。" },
  {
    id: 4,
    type: "text",
    content: "我刚刚看完一本非常有趣的书，推荐给大家！",
  },
  { id: 5, type: "photo", content: "https://example.com/photo2.jpg" },
  {
    id: 6,
    type: "text",
    content: "这是一条关于生活的小贴士，希望对你有帮助。",
  },
  {
    id: 7,
    type: "text",
    content: "学习新知识总是令人兴奋的，大家一起加油！",
  },
  { id: 8, type: "photo", content: "https://example.com/photo3.jpg" },
  {
    id: 9,
    type: "text",
    content: "今天晚上有一场精彩的电影，不要错过哦！",
  },
  {
    id: 10,
    type: "text",
    content: "在这个快节奏的社会中，保持内心的平静是非常重要的。",
  },
  { id: 11, type: "text", content: "新的一年，新的开始，祝大家好运！" },
  { id: 12, type: "photo", content: "https://example.com/photo4.jpg" },
  {
    id: 13,
    type: "text",
    content: "健康的饮食习惯是保持身体健康的关键。",
  },
  { id: 14, type: "text", content: "今天的工作进展顺利，心情很好！" },
  { id: 15, type: "photo", content: "https://example.com/photo5.jpg" },
  {
    id: 16,
    type: "text",
    content: "旅行是增长见识的好方法，大家一起去吧！",
  },
  { id: 17, type: "text", content: "读书可以开阔眼界，提升自我。" },
  { id: 18, type: "photo", content: "https://example.com/photo6.jpg" },
  {
    id: 19,
    type: "text",
    content: "晨跑是一个很好的锻炼方式，推荐给大家。",
  },
  { id: 20, type: "text", content: "保持积极的心态是成功的重要因素。" },
  { id: 21, type: "text", content: "今天我尝试了新的食谱，味道不错！" },
  { id: 22, type: "photo", content: "https://example.com/photo7.jpg" },
  { id: 23, type: "text", content: "学习外语可以帮助我们更好地沟通。" },
  {
    id: 24,
    type: "text",
    content: "每个人都有自己的梦想，努力去实现它！",
  },
  { id: 25, type: "photo", content: "https://example.com/photo8.jpg" },
  {
    id: 26,
    type: "text",
    content: "与朋友分享快乐是生活中最美好的事情。",
  },
  { id: 27, type: "text", content: "今天我参加了一个有趣的线上课程。" },
  { id: 28, type: "photo", content: "https://example.com/photo9.jpg" },
  { id: 29, type: "text", content: "保持乐观的态度能让生活更美好。" },
  { id: 30, type: "text", content: "我喜欢在周末去公园散步，放松心情。" },
  { id: 31, type: "text", content: "每天坚持运动，身体会更健康。" },
  { id: 32, type: "photo", content: "https://example.com/photo10.jpg" },
  { id: 33, type: "text", content: "今天的工作让我感到很有成就感。" },
  { id: 34, type: "text", content: "音乐是生活中不可或缺的一部分。" },
  { id: 35, type: "photo", content: "https://example.com/photo11.jpg" },
  { id: 36, type: "text", content: "我最近在学习摄影，拍了很多好照片。" },
  { id: 37, type: "text", content: "读书可以让我们更好地理解世界。" },
  { id: 38, type: "photo", content: "https://example.com/photo12.jpg" },
  { id: 39, type: "text", content: "保持好奇心是探索未知的动力。" },
  {
    id: 40,
    type: "text",
    content: "今天我尝试了新的锻炼方式，感觉不错！",
  },
  { id: 41, type: "text", content: "生活中要学会感恩，珍惜身边的人。" },
  { id: 42, type: "photo", content: "https://example.com/photo13.jpg" },
  { id: 43, type: "text", content: "我喜欢在闲暇时看电影，放松自己。" },
  {
    id: 44,
    type: "text",
    content: "今天我学到了一些新的技能，感觉很充实。",
  },
  { id: 45, type: "photo", content: "https://example.com/photo14.jpg" },
  { id: 46, type: "text", content: "与家人共度时光是最幸福的事情。" },
  {
    id: 47,
    type: "text",
    content: "我最近在尝试新的兴趣爱好，感觉很有趣。",
  },
  { id: 48, type: "photo", content: "https://example.com/photo15.jpg" },
  { id: 49, type: "text", content: "保持积极的心态能吸引更多的好运。" },
  { id: 50, type: "text", content: "我喜欢在周末去逛博物馆，增长见识。" },
  { id: 51, type: "text", content: "今天的工作让我感到很有成就感。" },
  { id: 52, type: "photo", content: "https://example.com/photo16.jpg" },
  { id: 53, type: "text", content: "我最近在学习烹饪，尝试做各种菜肴。" },
  { id: 54, type: "text", content: "每天坚持锻炼，身体会更加健康。" },
  { id: 55, type: "photo", content: "https://example.com/photo17.jpg" },
  { id: 56, type: "text", content: "与朋友分享快乐的时光是生活的乐趣。" },
  {
    id: 57,
    type: "text",
    content: "我喜欢在雨天里喝一杯热茶，享受宁静。",
  },
  { id: 58, type: "photo", content: "https://example.com/photo18.jpg" },
  { id: 59, type: "text", content: "每一天都是新的开始，充满无限可能。" },
  {
    id: 60,
    type: "text",
    content: "我最近在学习绘画，发现了自己的潜力。",
  },
  { id: 61, type: "text", content: "生活中要学会欣赏美好的事物。" },
  { id: 62, type: "photo", content: "https://example.com/photo19.jpg" },
  {
    id: 63,
    type: "text",
    content: "我喜欢在周末与朋友一起聚会，畅谈生活。",
  },
  { id: 64, type: "text", content: "保持好奇心是探索世界的动力。" },
  { id: 65, type: "photo", content: "https://example.com/photo20.jpg" },
  { id: 66, type: "text", content: "今天我参加了一个有趣的线上讲座。" },
  { id: 67, type: "text", content: "我喜欢在阳光明媚的日子里去海边。" },
  { id: 68, type: "photo", content: "https://example.com/photo21.jpg" },
  { id: 69, type: "text", content: "生活中要学会发现小幸福。" },
  {
    id: 70,
    type: "text",
    content: "我最近在尝试新的健身计划，期待效果。",
  },
  { id: 71, type: "text", content: "与家人共度时光是最幸福的事情。" },
  { id: 72, type: "photo", content: "https://example.com/photo22.jpg" },
  {
    id: 73,
    type: "text",
    content: "我喜欢在夏天的傍晚去散步，享受微风。",
  },
  { id: 74, type: "text", content: "每天都要给自己一些积极的鼓励。" },
  { id: 75, type: "photo", content: "https://example.com/photo23.jpg" },
  {
    id: 76,
    type: "text",
    content: "我最近在学习吉他，期待能演奏出动听的旋律。",
  },
  { id: 77, type: "text", content: "保持积极的心态能吸引更多的好运。" },
  { id: 78, type: "photo", content: "https://example.com/photo24.jpg" },
  { id: 79, type: "text", content: "我喜欢在冬天的晚上喝一杯热巧克力。" },
  { id: 80, type: "text", content: "每天都要努力追求自己的梦想。" },
  {
    id: 81,
    type: "text",
    content: "我最近在尝试新的摄影技巧，拍了很多好照片。",
  },
  { id: 82, type: "photo", content: "https://example.com/photo25.jpg" },
  { id: 83, type: "text", content: "与朋友一起旅行是最快乐的事情。" },
  {
    id: 84,
    type: "text",
    content: "我喜欢在周末去市场，寻找新鲜的食材。",
  },
  { id: 85, type: "photo", content: "https://example.com/photo26.jpg" },
  { id: 86, type: "text", content: "保持好奇心是探索世界的动力。" },
  {
    id: 87,
    type: "text",
    content: "我最近在学习新的编程语言，感觉很有趣。",
  },
  { id: 88, type: "photo", content: "https://example.com/photo27.jpg" },
  { id: 89, type: "text", content: "生活中要学会欣赏身边的小美好。" },
  {
    id: 90,
    type: "text",
    content: "我喜欢在秋天的公园里散步，欣赏落叶。",
  },
  { id: 91, type: "text", content: "每天都要给自己一些积极的鼓励。" },
  { id: 92, type: "photo", content: "https://example.com/photo28.jpg" },
  {
    id: 93,
    type: "text",
    content: "我最近在尝试新的烹饪技巧，期待能做出美味的菜肴。",
  },
  { id: 94, type: "text", content: "与家人共度时光是最幸福的事情。" },
  { id: 95, type: "photo", content: "https://example.com/photo29.jpg" },
  {
    id: 96,
    type: "text",
    content: "我喜欢在春天的花园里散步，享受花香。",
  },
  { id: 97, type: "text", content: "每天都要努力追求自己的梦想。" },
  {
    id: 98,
    type: "text",
    content: "我最近在学习新的语言，感觉很有挑战性。",
  },
  { id: 99, type: "photo", content: "https://example.com/photo30.jpg" },
  { id: 100, type: "text", content: "生活中要学会发现小幸福。" },
  {
    id: 101,
    type: "text",
    content: "我喜欢在周末与朋友一起聚会，畅谈生活。",
  },
  { id: 102, type: "photo", content: "https://example.com/photo31.jpg" },
  { id: 103, type: "text", content: "保持好奇心是探索未知的动力。" },
  {
    id: 104,
    type: "text",
    content: "我最近在学习新的技能，期待能有所收获。",
  },
  { id: 105, type: "photo", content: "https://example.com/photo32.jpg" },
  {
    id: 106,
    type: "text",
    content: "与朋友分享快乐的时光是生活的乐趣。",
  },
  { id: 107, type: "text", content: "我喜欢在阳光明媚的日子里去海边。" },
  { id: 108, type: "photo", content: "https://example.com/photo33.jpg" },
  { id: 109, type: "text", content: "生活中要学会欣赏美好的事物。" },
  {
    id: 110,
    type: "text",
    content: "我最近在学习绘画，发现了自己的潜力。",
  },
  { id: 111, type: "photo", content: "https://example.com/photo34.jpg" },
  {
    id: 112,
    type: "text",
    content: "我喜欢在雨天里喝一杯热茶，享受宁静。",
  },
  { id: 113, type: "text", content: "每天都要给自己一些积极的鼓励。" },
  { id: 114, type: "photo", content: "https://example.com/photo35.jpg" },
  {
    id: 115,
    type: "text",
    content: "我最近在学习吉他，期待能演奏出动听的旋律。",
  },
  { id: 116, type: "text", content: "保持积极的心态能吸引更多的好运。" },
  { id: 117, type: "photo", content: "https://example.com/photo36.jpg" },
  {
    id: 118,
    type: "text",
    content: "我喜欢在冬天的晚上喝一杯热巧克力。",
  },
  { id: 119, type: "text", content: "每天都要努力追求自己的梦想。" },
  {
    id: 120,
    type: "text",
    content: "我最近在尝试新的摄影技巧，拍了很多好照片。",
  },
  { id: 121, type: "photo", content: "https://example.com/photo37.jpg" },
  { id: 122, type: "text", content: "与朋友一起旅行是最快乐的事情。" },
  {
    id: 123,
    type: "text",
    content: "我喜欢在周末去市场，寻找新鲜的食材。",
  },
  { id: 124, type: "photo", content: "https://example.com/photo38.jpg" },
  { id: 125, type: "text", content: "保持好奇心是探索世界的动力。" },
  {
    id: 126,
    type: "text",
    content: "我最近在学习新的编程语言，感觉很有趣。",
  },
  { id: 127, type: "photo", content: "https://example.com/photo39.jpg" },
  { id: 128, type: "text", content: "生活中要学会欣赏身边的小美好。" },
  {
    id: 129,
    type: "text",
    content: "我喜欢在秋天的公园里散步，欣赏落叶。",
  },
];
